# Generated by Django 5.0.3 on 2024-03-23 20:49

import FitnessApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

   # operations = [
     #   migrations.AddField(
     #       model_name='userprofile',
      #      name='picture',
      #      field=models.ImageField(blank=True, upload_to=FitnessApp.models.getcurrentusername),
      #  ),
   # ]
